# Generated by Django 4.2.7 on 2024-01-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_like_post_alter_post_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
