# Generated by Django 4.2.7 on 2024-01-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_datetime_post_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
